# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0dcc2c1a7fc46545baa288bba45c846f6019e4cdee3c201325528d79ac6c6762220e68210869f3aac36135e5b0b39580b66e0851d96d0cfd239ccb5766a6f1a1

test:
  secret_key_base: 89c354d0092e59069cc3425e46883d997d8c85e14bab88a77c7aab868ef5271367aea7a5063b69264fecdaa628e4071efa7126045ceec1231ab73850915bb2d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
